### ISSUE TITLE
Streaming a user

### ISSUE THREAD

**Issue by elliottmorris** [mispy/twitter_ebooks#122]
Is there  a way i can open a user stream and reply to any of their new tweets that meet certain parameters? 

IE: Could I open a user stream of my main twitter account and have it respond to any tweet that mentions "bot"? Simpler, could it just respond to any tweet? 

Thanks

**Comment by negatendo** [comment]
Yes it's possible to "cyborg" your own account using twitter_ebooks if that's what you want to do. Just authorize the bot to post to your own twitter instead of a new account. Then write your behaviors accordingly. You'll want to utilize on_timeline() to match and reply to tweets directed at your account.
